# Generated by Django 3.2.6 on 2021-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('MechanicID', models.AutoField(primary_key=True, serialize=False)),
                ('District', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('Contact', models.CharField(max_length=11)),
            ],
        ),
    ]
